### ISSUE TITLE
I can't see disqus comments. 

### ISSUE THREAD

**Issue by jinseob2kim** [rstudio/radix#30] opened 2018-09-26 03:09 UTC
Hello, I am jinseob Kim.

I make my blog using radix (https://blog.anpanman.co.kr)

But, I can't show disqus comments when clicking comments button  (https://blog.anpanman.co.kr/posts/2018-09-25-welcome/).

This problem is solved by  changing browser's size.

There is same problem in Reproducible Finance with R(https://beta.rstudioconnect.com/content/3776/posts/2017-11-09-visualizing-asset-returns/)

But, this problem doesn't occur in TensorFlow for R blog(https://blogs.rstudio.com/tensorflow/posts/2018-09-17-eager-captioning/)

Can I solve this problem?

Sincerely.

**Comment by jjallaire** [comment] 2018-09-26 12:11
I'm not able to reproduce this (I can see the comments when going fullscreen in Chrome).

**Comment by jjallaire** [comment] 2018-09-26 12:32
Okay, the platform info helped. I can reproduce this on Ubuntu but not on OS X or Windows. I'll see if there is a fix possible (but it could be an Ubuntu-specific Chrome rendering bug)

**Comment by jinseob2kim** [comment] 2018-09-26 12:41
> Okay, the platform info helped. I can reproduce this on Ubuntu but not on OS X or Windows. I'll see if there is a fix possible (but it could be an Ubuntu-specific Chrome rendering bug)

There is a same problem in my windows7 laptop with internet explorer 11.0.9600.19100IS.

Thanks!

**Comment by jjallaire** [comment] 2018-09-26 13:03
I have a speculative fix for this here: https://github.com/rstudio/radix/commit/d7b910009fae07c9d42ece46f71deaba3f4e031a

Basically triggering the window.resize() event after the click to try to get Chrome to repaint properly.

**Comment by jjallaire** [comment] 2018-09-26 13:03
I'm also no longer able to reproduce the problem on Ubuntu (no idea what changed, but in full screen mode the comments now show up as expected)

**Comment by jinseob2kim** [comment] 2018-09-26 13:42
> I'm also no longer able to reproduce the problem on Ubuntu (no idea what changed, but in full screen mode the comments now show up as expected)

Unfortunately, I'm still suffering the issues in my ubuntu & window7 laptops after updating the package.

Can you give a option to change default comments mode (hidden vs show)?

After manually changing the option `hidden` to `show`, I always see the comments.

Sincerely.

**Comment by jjallaire** [comment] 2018-09-26 14:55
Okay, this option is implemented here: https://github.com/rstudio/radix/commit/c5cd3eefb3369c6622dc1eb5a5b7c66b91d7606b

Docs are here: https://rstudio.github.io/radix/blog.html#comments-and-sharing

**Closed by jjallaire** 2018-09-26 14:55 UTC

**Comment by jinseob2kim** [comment] 2018-09-26 15:16
> Okay, this option is implemented here: [c5cd3ee](https://github.com/rstudio/radix/commit/c5cd3eefb3369c6622dc1eb5a5b7c66b91d7606b)
> 
> Docs are here: https://rstudio.github.io/radix/blog.html#comments-and-sharing

I apply this option to my blog. Thanks a lot!!!

**Comment by dsaada** [comment] 2018-12-06 14:21
ji,
we need to to a manipulation on disqus web site before to print on our blog?
thx
David

**Comment by dsaada** [comment] 2018-12-06 19:59
I use the package on github, it does not work for me, I get the same issues of jinseob2kim
