### ISSUE TITLE
Relative path to bibliography does not work

### ISSUE THREAD

**Issue by WillemSleegers** [rstudio/radix#34] opened 2018-09-27 11:55 UTC
When I specify a relative path to a .bib file, it doesn't work.

This works:
`bibliography: library.bib`

This does not work:
`bibliography: ../../static/bib/library.bib`

I do not get an error message, but it simply does not produce the citations. An illustration of this can be seen here: https://rstudio.github.io/radix/basics.html#citations. The citation there does not show, although it does show here: https://rstudio.github.io/radix/citations.html

**Comment by jjallaire** [comment] 2018-09-27 12:14
The example you cite was actually not caused by a relative path, but rather the absence of a `bibliography` entry in the basics.Rmd file. That's now been fixed. 

I'll look into the other issue and report back soon.

**Comment by jjallaire** [comment] 2018-09-27 12:19
I'm unable to reproduce the problem with relative paths in `bibliography` (for me the bibliography is found and the citations displayed). Could you provide a minimal reproducible example of code that's failing for you as well as let me know the results of `sessionInfo()` on your system.

**Comment by WillemSleegers** [comment] 2018-09-28 09:16
The issue appears to occur when it's a blog, rather than a stand-alone Radix article.
[Reprex Blog.zip](https://github.com/rstudio/radix/files/2427562/Reprex.Blog.zip)

**Comment by WillemSleegers** [comment] 2018-09-28 09:33
Update: I think my problem was that I had no build the website yet, and that's why it went wrong! 

I think this issue can be closed now.

**Comment by jjallaire** [comment] 2018-09-28 13:33
Thanks for the reprex! It should still work when you haven't yet built the site so that is in fact a bug. Should be fixed here: https://github.com/rstudio/radix/commit/47db5c497bdeafd1fa3445666630ca83b050f0d6

**Closed by jjallaire** 2018-09-28 13:33 UTC
